### ISSUE TITLE
Strange behavior from stderr

### ISSUE THREAD

**Issue by npe9** [HobbesOSR/kitten#6]
attempts to write to stderr from openmpi are causing sys_write to go through the pipe code path. Since kitten expects a valid mutex for pipes I am getting a kernel fault when the uninitialized mutex is locked.

I've hacked around it in the short term (redirecting stderr to stdout) but I will fix it after MPI is working multinode.

**Comment by ktpedre** [comment]
Closing, please reopen if this is still an issue.
